# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PutioSync < Formula
  desc "Put.io folder sync app"
  homepage "https://github.com/putdotio/putio-sync"
  version "2.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/putdotio/putio-sync/releases/download/v2.1.3/putio-sync_2.1.3_darwin_amd64.tar.gz"
      sha256 "323e775018a486a556ff8fe4330c16e539ce6b3068bd971f9f8dd5a9c49b49a1"

      define_method(:install) do
        bin.install "putio-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/putdotio/putio-sync/releases/download/v2.1.3/putio-sync_2.1.3_darwin_arm64.tar.gz"
      sha256 "dee163a044e4c300e63b965a1fefc1670ad51ea498329350a315be075d55d290"

      define_method(:install) do
        bin.install "putio-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/putdotio/putio-sync/releases/download/v2.1.3/putio-sync_2.1.3_linux_amd64.tar.gz"
      sha256 "73fc57732a5952957c6666c05a2ce90866876a557b620e69cd62a881e98b36a7"
      define_method(:install) do
        bin.install "putio-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/putdotio/putio-sync/releases/download/v2.1.3/putio-sync_2.1.3_linux_arm64.tar.gz"
      sha256 "ad4eaf45a49e4fb02cb2d30e6e042a3e09ed061d373fe66cb8a029cf9b8a6ab2"
      define_method(:install) do
        bin.install "putio-sync"
      end
    end
  end

  test do
    system "#{bin}/putio-sync -version"
  end
end
