# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class PutioCli < Formula
  desc "Agent-first cli for the put.io api"
  homepage "https://github.com/putdotio/putio-cli"
  url "https://github.com/putdotio/putio-cli/archive/refs/tags/v1.2.5.tar.gz"
  sha256 "ff85ec97fb592d938d33270050ab6f768521cfc13e21214235d5a9c3f7b615a3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/putdotio/putio-cli/releases/download/v1.2.5/putio-cli-1.2.5-darwin-arm64.tar.gz"
      sha256 "5645ca85c2e0adeb033a230674746742ffba544a733e67fcf5cd9b6517c28b34"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/putdotio/putio-cli/releases/download/v1.2.5/putio-cli-1.2.5-linux-amd64.tar.gz"
      sha256 "f28545ac4a51ef31de873d40c6a979484468d9370460a9e24b04d0205d9f4889"
    end
  end

  def install
    bin.install "putio"
  end

  test do
    output = shell_output("#{bin}/putio version")
    assert_match "putio", output
    assert_match version.to_s, output
  end
end
