# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PutioSync < Formula
  desc "Put.io folder sync app"
  homepage "https://github.com/putdotio/putio-sync"
  version "2.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/putdotio/putio-sync/releases/download/v2.1.4/putio-sync_2.1.4_darwin_amd64.tar.gz"
      sha256 "63c4dd421eba8cb66c5da5e86b454ad67f59f21c7de04700d2c2b3b88db100d3"

      define_method(:install) do
        bin.install "putio-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/putdotio/putio-sync/releases/download/v2.1.4/putio-sync_2.1.4_darwin_arm64.tar.gz"
      sha256 "dc75f74e31de6cf2edda3fc38b98f2856881f2d0cf4395ccff31ac0a936654bd"

      define_method(:install) do
        bin.install "putio-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/putdotio/putio-sync/releases/download/v2.1.4/putio-sync_2.1.4_linux_amd64.tar.gz"
      sha256 "16f2a25fbc4c7710ce1410959bec139a11f7b742ad4497bfc566798077d9e171"
      define_method(:install) do
        bin.install "putio-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/putdotio/putio-sync/releases/download/v2.1.4/putio-sync_2.1.4_linux_arm64.tar.gz"
      sha256 "a8123d74ca6df0c6a25ac0d3dffe3061eece247c6a2095c2c8030acce53970e5"
      define_method(:install) do
        bin.install "putio-sync"
      end
    end
  end

  test do
    system "#{bin}/putio-sync -version"
  end
end
