# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class PutioCli < Formula
  desc "Agent-first cli for the put.io api"
  homepage "https://github.com/putdotio/putio-cli"
  url "https://github.com/putdotio/putio-cli/archive/refs/tags/v1.4.0.tar.gz"
  sha256 "60565ddd4c483df1fa7fc5e14cc2be19dfe29ebdf170fed334d10e8e7d5aab52"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/putdotio/putio-cli/releases/download/v1.4.0/putio-cli-1.4.0-darwin-arm64.tar.gz"
      sha256 "b489fc43bf410a539a3242e5b771488cab47c9297bcb581df27498fe3fcaeac5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/putdotio/putio-cli/releases/download/v1.4.0/putio-cli-1.4.0-linux-amd64.tar.gz"
      sha256 "c7ae8b76ab598e3e19e26c33d72403eacbae476e59aaf0de73a943d4c5839d4b"
    end
  end

  def install
    bin.install "putio"
  end

  test do
    output = shell_output("#{bin}/putio version")
    assert_match "putio", output
    assert_match version.to_s, output
  end
end
