# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class PutioCli < Formula
  desc "Agent-first cli for the put.io api"
  homepage "https://github.com/putdotio/putio-cli"
  url "https://github.com/putdotio/putio-cli/archive/refs/tags/v1.7.1.tar.gz"
  version "1.7.1"
  sha256 "32e45c4cb7c32abc39d2e311ffd5f9d82e07445b308140a8b9b69ea966c666e0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/putdotio/putio-cli/releases/download/v1.7.1/putio-cli-1.7.1-darwin-arm64.tar.gz"
      sha256 "f29c990dc85573f0def95fe6c1aed20b1b5e62b7172e6a02536dc8f9df354f7c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/putdotio/putio-cli/releases/download/v1.7.1/putio-cli-1.7.1-linux-amd64.tar.gz"
      sha256 "3ede3a4af73e5b027aab96fd5211a2284132e443a5c5c1d2d01ea0d61bd45877"
    end
  end

  def install
    bin.install "putio"
  end

  test do
    output = shell_output("#{bin}/putio version")
    assert_match "putio", output
    assert_match version.to_s, output
  end
end
