# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PutioSync < Formula
  desc "Put.io folder sync app"
  homepage "https://github.com/putdotio/putio-sync"
  version "2.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/putdotio/putio-sync/releases/download/v2.1.2/putio-sync_2.1.2_darwin_amd64.tar.gz"
      sha256 "9835bb003851a3f04d71f87042ae8211c540c34ce2b09564aec7e526fed9a136"

      define_method(:install) do
        bin.install "putio-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/putdotio/putio-sync/releases/download/v2.1.2/putio-sync_2.1.2_darwin_arm64.tar.gz"
      sha256 "2da5d505921fff2949e52a5176a52643c55a3e21d80d1ae082a1c4d7bbe0ba31"

      define_method(:install) do
        bin.install "putio-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/putdotio/putio-sync/releases/download/v2.1.2/putio-sync_2.1.2_linux_amd64.tar.gz"
      sha256 "01a99fec0196ab3a3450f33b23525c20e24de90fa562005e64a05244bdc73485"
      define_method(:install) do
        bin.install "putio-sync"
      end
    end
  end

  test do
    system "#{bin}/putio-sync -version"
  end
end
